
project_id = "yzrovzblelpnftlegczx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
js_port = 54323
major_version = 15

[studio]
enabled = true
port = 54324

[inbucket]
enabled = true
port = 54325

[functions]
enabled = true
port = 54328

[functions.v1]
sdk_version = "2.0.0"

[functions.uploadGuide]
verify_jwt = true

[functions.uploadDemonstrative]
verify_jwt = true

[functions.generate-contestation]
verify_jwt = true

[storage]
enabled = true
file_size_limit = "50MiB"
upload_file_limit = 100

[realtime]
enabled = true

[auth]
enable_signup = true
