
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzrovzblelpnftlegczx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6cm92emJsZWxwbmZ0bGVnY3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NTc1MzksImV4cCI6MjA2MDMzMzUzOX0.wEvwIk_suF0uLWkGfMBa2XHmjvN4CySk58aoz24uun8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    storage: localStorage
  },
  global: {
    headers: {
      'Content-Type': 'application/json'
    }
  }
});

// Add session token to global headers when available
supabase.auth.onAuthStateChange((event, session) => {
  if (session?.access_token) {
    console.log("Auth state change:", event);
    supabase.functions.setAuth(session.access_token);
  }
});

// Debugging helper for authentication
if (typeof window !== 'undefined') {
  (window as any).getSupabaseSession = async () => {
    const { data, error } = await supabase.auth.getSession();
    console.log("Current session:", data.session, error);
    return { data, error };
  };

  // Helper functions for testing
  (window as any).createTestUser = async () => {
    const testEmail = `test${Math.floor(Math.random() * 10000)}@example.com`;
    const testPassword = "Password123!";
    
    const { data, error } = await supabase.auth.signUp({
      email: testEmail,
      password: testPassword,
    });
    
    console.log("Test user created:", { email: testEmail, password: testPassword }, data, error);
    return { email: testEmail, password: testPassword, data, error };
  };

  // Direct login method for testing
  (window as any).loginWithPassword = async (email: string, password: string) => {
    const { data, error } = await supabase.auth.signInWithPassword({
      email,
      password,
    });
    
    console.log("Login result:", data, error);
    return { data, error };
  };
}
