
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzrovzblelpnftlegczx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6cm92emJsZWxwbmZ0bGVnY3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NTc1MzksImV4cCI6MjA2MDMzMzUzOX0.wEvwIk_suF0uLWkGfMBa2XHmjvN4CySk58aoz24uun8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  global: {
    headers: {
      'Content-Type': 'application/json'
    }
  }
});

// Add session token to global headers when available
supabase.auth.onAuthStateChange((event, session) => {
  if (session?.access_token) {
    supabase.functions.setAuth(session.access_token);
  }
});
